# Generated by Django 4.2.2 on 2023-07-28 15:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('snippet', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('prep_time', models.CharField(blank=True, max_length=200, null=True)),
                ('cook_time', models.CharField(blank=True, max_length=200, null=True)),
                ('proof_time', models.CharField(blank=True, max_length=200, null=True)),
                ('serves', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredients', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('method', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('story_time', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(related_name='recipes', to='recipes.category')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
