# Generated by Django 4.2.2 on 2023-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_story_time_alter_recipe_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, default='uncategorised', max_length=150, null=True),
        ),
    ]
