# Generated by Django 4.2.2 on 2023-06-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_postcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='Category',
        ),
    ]
