# Generated by Django 4.2.2 on 2023-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0002_remove_recipe_information_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, default='uncategorised', max_length=150, null=True),
        ),
    ]
