# Generated by Django 4.2.2 on 2023-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0003_category_alter_recipe_options_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('bread', 'bread'), ('cakes', 'cakes'), ('biscuits', 'biscuits')], default='uncategorised', max_length=150, null=True),
        ),
    ]
